In [23]:
import numpy as np

ARITHMATIC OPERATIONS

In [24]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [25]:
arr2 = a1 + a2
arr2

array([ 7,  9, 11, 13, 15])

In [26]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [27]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [28]:
a1 /a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [29]:
a1 //a2

array([0, 0, 0, 0, 0])

In [30]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

BROADCASTING

In [31]:
l = [10,20,30,40]
arr = np.array(l)

In [32]:
arr + 10

array([20, 30, 40, 50])

In [33]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

DEEP AND  SHALLOW COPY

In [35]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
slice = a[:5]
slice  = slice * 10
slice

array([10, 20, 30, 40, 50])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

MATRIX OPERATION

In [40]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [41]:
A

array([[1, 2],
       [3, 4]])

In [42]:
B

array([[5, 6],
       [7, 8]])

In [43]:
A @ B #Dot product in matrix

array([[19, 22],
       [43, 50]])

In [44]:
A.T  #Transpose of matrix

array([[1, 3],
       [2, 4]])

ADVANCE ARRAY MANIPULATION

Stacking Array

In [45]:
a  = np.array([1,2,3,4])
b = np.array([5,6,7,8])