In [4]:
import numpy as np


Basic Array Creation


In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3.5,"hello"]
a

[1, 2, 3.5, 'hello']

In [7]:
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [8]:
l = [[1,2,3] , [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARRAY GENERATION FUNCTION

In [10]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [15]:
arr = np.linspace(0,1,25)
arr

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

RANDOM GENERATION FUNCTION

In [ ]:
np.random.rand(10) #The value will come between 0 and 1  this is called Normalization.

array([0.81735236, 0.07076954, 0.77294028, 0.32367067, 0.74770196,
       0.92937577, 0.2959335 , 0.1446643 , 0.64127625, 0.19570075])

In [17]:
np.random.randn(10) # The value will be generated betwwen -3 to +3, called as Standrization

array([-0.68617674, -0.94837328, -0.12194413,  0.77037833,  1.1065213 ,
        0.99886864, -0.08523984,  0.2416693 , -0.65452505,  0.95783959])

In [18]:
np.random.randint(10,20,10)  #(start, end, numbers b/w start and end)

array([19, 15, 10, 17, 11, 18, 11, 12, 17, 14], dtype=int32)

ARRAY ATTRIBUTES

In [21]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape  #attributes are called directly

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

ARRAY METHODS

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis = 0) #sum of the column

array([12, 15, 18])

In [30]:
np.sum(arr,axis = 1) #sum of the row

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [32]:
arr.std()

np.float64(2.581988897471611)

In [33]:
arr.argmin()

np.int64(0)

In [34]:
arr.argmax()

np.int64(8)

RESHAPING AND RESIZING

In [35]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [39]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])