In [1]:
import numpy as np

NUMPY INDEXING AND SLICING OF VECTORS

In [4]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[6]   #using index value to print the required number

np.int64(17)

In [8]:
arr_slice = arr[3:9:2]
arr_slice

array([14, 16, 18])

NUMPY INDEXING AND SLICING OF MATRIX

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[5] #Finding the array of the row by its index

array([26, 27, 28, 29, 30])

In [13]:
arr[0,4]

np.int64(5)

In [15]:
slice = arr[0:2,1:3] #slicing a portion from matrix
slice

array([[2, 3],
       [7, 8]])

In [16]:
slice = arr[3:6,3:5]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

BOOLEAN INDEXING

In [17]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [19]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])